### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by pedrolamas** [Neilpang/letsproxy#1]
Sorry for being direct, but I've been trying to make this work for the past couple of hours with limited success...

I see the generated certificates inside the "/nginx/acme" folder, but nothing on "/nginx/certs".

Here's my docker-compose.yml file (with changed domain):

```
version: '3.7'

services:
  adguardhome:
    depends_on: 
      - nginx
    image: adguard/adguardhome:arm64-latest
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.3
    volumes:
      - "./adguardhome/work:/opt/adguardhome/work"
      - "./adguardhome/conf:/opt/adguardhome/conf"
    environment:
      - VIRTUAL_HOST=my.domain.com
      - ENABLE_ACME=true
    dns:
      - 127.0.0.1
      - 1.1.1.1
  
  nginx:
    image: neilpang/nginx-proxy
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.4
    ports:
      - "20080:80"
      - "20443:443"
      # - "10853:853"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx/certs:/etc/nginx/certs"
      - "./nginx/acme:/acmecerts"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/stream.d:/etc/nginx/stream.d"
      - "./nginx/dhparam:/etc/nginx/dhparam"
    env_file: ./nginx/docker/secrets.env

networks:
  backbone:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27
```

The secret.env file above contains the environment variables for Cloudflare.
